### ISSUE TITLE
update_collection_extent setting results in wrong JSON structure

### ISSUE THREAD

**Issue by jonas-eberle** [stac-utils/pgstac#274] opened 2024-05-31 10:26 UTC
I have tried to set the option `update_collection_extent` to `true`, but this results in wrong JSON when the partition stats are updated. 

The following function creates the wrong JSON: 
https://github.com/stac-utils/pgstac/blob/0c8874113475a7bfc32a3196bc3d1e6101372e05/src/pgstac/sql/003b_partitions.sql#L168-L180

This results in the following code with an additional extent key: 
```
  "extent": {
    "extent": {
      "spatial": {
        "bbox": [
          [
            -180,
            -90,
            180,
            90
          ]
        ]
      },
      "temporal": {
        "interval": [
          [
            "2000-02-01T00:00:00+00:00",
            "2024-03-31T23:59:59+00:00"
          ]
        ]
      }
    }
  },
```

**Comment by olivegak971** [comment] 2024-05-31 11:01
I've noticed the same behaviour on my side

**Comment by olivegak971** [comment] 2024-05-31 13:44
I've found a solution. You need to create the following SQL script to replace the function collection_extent : 

CREATE OR REPLACE FUNCTION collection_extent(_collection text, runupdate boolean default false) RETURNS jsonb AS $$
DECLARE
    geom_extent geometry;
    mind timestamptz;
    maxd timestamptz;
    extent jsonb;
BEGIN
    IF runupdate THEN
        PERFORM update_partition_stats_q(partition)
        FROM partitions_view WHERE collection=_collection;
    END IF;
    SELECT
        min(lower(dtrange)),
        max(upper(edtrange)),
        st_extent(spatial)
    INTO
        mind,
        maxd,
        geom_extent
    FROM partitions_view
    WHERE collection=_collection;

    IF geom_extent IS NOT NULL AND mind IS NOT NULL AND maxd IS NOT NULL THEN
        extent := jsonb_build_object(
                'spatial', jsonb_build_object(
                    'bbox', to_jsonb(array[array[st_xmin(geom_extent), st_ymin(geom_extent), st_xmax(geom_extent), st_ymax(geom_extent)]])
                ),
                'temporal', jsonb_build_object(
                    'interval', to_jsonb(array[array[mind, maxd]])
                )
        );
        RETURN extent;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE PLPGSQL;

**Comment by zacharyDez** [comment] 2024-06-03 17:45
We found the duplicate of the extent key in `003b_partitions.sql` here: https://github.com/stac-utils/pgstac/blob/a9b71b524d3853316c96391ea8d92fc3f6191d4a/src/pgstac/sql/003b_partitions.sql#L174C1-L175C1

**Closed** 2024-06-04 16:29 UTC
